<?php foreach ($servers as $groupName => $group) : ?>
	<h4 class="content text-M" style="margin-bottom: 0px; padding-bottom: 0px;"><?php echo $groupName; ?></h4>
	<?php foreach ($group as $server) : ?>
		<div class="panel">
			<span class="text-S" style="width: 100px; display: inline-block; overflow: hidden; text-overflow: ellipsis; white-space: nowrap;"><?php echo $server['name']; ?></span>
			<div class="label-group">
				<span class="<?php echo $server['class_on']; ?>">on</span><span class="<?php echo $server['class_off']; ?>">off</span>
			</div>
		</div>
	<?php endforeach; ?>
<?php endforeach; ?>