<div class="widget-body">
<ul class="matrix four-col">
<?php foreach ($targetStats as $stat) : ?>
<li>
  <div class="panel">
    <div>
      <span class="text-M"><?php echo $stat['name']?></span><br />
      <?php echo $stat['unit']; ?>, max: <?php echo $stat['max']; ?>, min: <?php echo $stat['min']; ?>
    </div>
    <div style="position: relative;">
      <span class="text-L" style="color: #<?php echo $stat['color']?>"><?php echo $stat['avg']; ?></span>
        <?php if ($stat['img-link']) : ?>
            <a href="<?php echo $stat['img-link'] ?>">
                <img src="<?php echo $stat['img']; ?>" />
            </a>
        <?php else :  ?>
            <img src="<?php echo $stat['img']; ?>" style="position: absolute; right: 10px" />
        <?php endif; ?>
    </div>
  </div>
</li>
<?php endforeach; ?>
</ul>
</div>
