<?php foreach ($targetStats as $stat) : ?>
    <div class="panel">
        <span class="text-XL" style="color: #<?php echo $stat['color']?>"><?php echo $stat['avg']; ?></span>
        <div style="display: inline-block; margin-left: 4px">
            <span class="text-M"><?php echo $stat['name']?></span><br />
            <?php echo $stat['unit']; ?>, <span class="<?php echo $stat['class']; ?>"><?php echo $stat['delta']; ?></span>
        </div>
        <img src="<?php echo $stat['img']; ?>" style="float: right" />
    </div>
<?php endforeach; ?>
