<?php
if (empty($servers)) {
	return;
}
?>
<div class="panel">
    <p class="text-M"><span class="text-L"><?php echo count($servers);?></span> Hot Servers</p>
</div>
<?php foreach ($servers as $server) : ?>
<div class="panel">
    <span class="text-L"><?php echo $server['name']?></span> (<?php echo $server['state']?>)<br />
    <table style="border: 0px" class="simple">
        <colgroup>
            <col class="t20">
            <col>
            <col class="t20">
            <col>
            <col class="t20">
            <col>
        </colgroup>
        <tr>
            <th colspan="6">CPU load</th>
        </tr>
        <tr>
            <th class="right">user:</th>
            <td class="negative"><?php echo $server['cpu']['user']; ?>%</td>
            <th class="right">nice:</th>
            <td><?php echo $server['cpu']['nice']; ?>%</td>
            <th class="right">sys:</th>
            <td><?php echo $server['cpu']['sys']; ?>%</td>
        </tr>
        <tr>
            <th class="right">iowait:</th>
            <td><?php echo $server['cpu']['iowait']; ?>%</td>
            <th class="right">irq:</th>
            <td><?php echo $server['cpu']['irq']; ?>%</td>
            <th class="right">softirq:</th>
            <td><?php echo $server['cpu']['softirq']; ?>%</td>
        </tr>
        <tr>
            <th class="right">idle:</th>
            <td><?php echo $server['cpu']['idle']; ?>%</td>
            <th class="right"></th>
            <td></td>
            <th class="right"></th>
            <td></td>
        </tr>

        <tr>
            <th colspan="6">Memory Usage</th>
        </tr>
        <tr>
            <th class="right">real:</th>
            <td><?php echo $server['memory']['real']; ?>%</td>
            <th class="right">buffer:</th>
            <td><?php echo $server['memory']['buffer']; ?>MB</td>
            <th class="right">cache:</th>
            <td><?php echo $server['memory']['cache']; ?>MB</td>
        </tr>
        <tr>
            <th class="right">swap:</th>
            <td><?php echo $server['memory']['swap']; ?>%</td>
            <th class="right"></th>
            <td></td>
            <th class="right"></th>
            <td></td>
        </tr>

        <tr>
            <th colspan="6">LAN</th>
        </tr>
        <tr>
            <th class="right">rta:</th>
            <td><?php echo $server['lan']['rta']; ?></td>
            <th class="right">lost:</th>
            <td><?php echo $server['lan']['lost']; ?></td>
            <th class="right"></th>
            <td></td>
        </tr>
    </table>
</div>
<?php endforeach; ?>