<?php
//$p = $this->kernel->getConfig();
//$p = empty($p['public']) ? '' : $p['public'];
$p = '';
function get_face($mood = 'positive') {
    $faces = array(
        'positive' => array('byebye', 'big_smile', 'haha', 'beauty', 'boss', 'feel_good'),
        'neutral' => array('angry', 'confuse'),
        'negative' => array('after_boom', 'ah', 'beat_brick', 'beat_shot', 'beat_plaster', 'beated'),
        'building' => array('matrix'),
    );

    srand(microtime(true)*1000000);
    $basePath = '/static/templates/hoborg/gfx/faces/';
    $randFaceIndex = rand(0, count($faces[$mood])-1);

    return $basePath . $faces[$mood][$randFaceIndex] . '.png';
}
?>
<ul class="matrix <?php echo $config['view-config']['cols'] ?>">
<?php foreach ($jobs as $job) : ?>
    
    <?php
    if (0 === strpos($job['name'], 'release-')) { continue; }
    $extras = '';

    $stateClass = '';
    $mood = 'neutral';
    if ('SUCCESS' == $job['lastBuild']['result']) {
        $mood = 'positive';
        $stateClass = 'text-M';
    }
    if ('UNSTABLE' == $job['lastBuild']['result']) {
        $mood = 'negative';
        $stateClass = 'text-M';
    }
    if ('FAILURE' == $job['lastBuild']['result']) {
        $mood = 'negative';
        $stateClass = 'text-M';
        if (true === $job['inQueue']) {
            $extras = 'Waiting in build queue';
        }
    }

    if ('ABORTED' === $job['lastBuild']['result']) {
        $mood = 'neutral';
        $stateClass = 'text-M';
        $extras = 'Aborted and IN QUEUE!';

        if (false === $job['inQueue']) {
            $mood = 'negative';
            $stateClass = 'text-M';
            $extras = 'Aborted and NOT IN QUEUE!';
        }
    }

    if ($job['lastBuild']['building']) {
        $job['lastBuild']['result'] = 'BUILDING';
        $mood = 'building';
        $extras = 'Building ...';
        $stateClass = 'text-M ';
    }
    ?>

    <li>
    <div style="height: auto"
        class="panel build-<?php echo $mood; ?>"
    >
        <img src="<?php echo $p . get_face($mood); ?>" height="40" style="float:left; margin: 0px 10px 0px 5px;" />
        <div>
            <span class="<?php echo $stateClass .' ' . $mood; ?>"><?php echo $job['name'] ?></span><br />
            <?php if (!empty($extras)) : ?>
                <span class="text-M"><?php echo $extras; ?></span><br />
            <?php endif; ?>
            build: <?php echo $job['lastBuild']['number'] ?>,
            date: <?php echo date('M d H:i', $job['lastBuild']['timestamp']/1000); ?>,
            health: <?php echo $job['healthReport'][0]['score']; ?>/100
        </div>
    </div>
    </li>
<?php endforeach; ?>
</ul>